### ISSUE TITLE
Unreadable text in overlay with dark mode enabled

### ISSUE THREAD

**Issue by lamka02sk** [jscher2000/View-Image-Info-Reborn-for-Firefox#1]
The text in overlaid more is the same color as background.

![Screenshot_20210502_150249](https://user-images.githubusercontent.com/8135372/116814123-7813cc80-ab57-11eb-8732-d02da0f3be3f.png)

**Comment by jscher2000** [comment]
Sorry about that, it is difficult to avoid website styles overriding mine. I need to learn about shadow trees and such, but... for now I'm just going to !important a bunch of rules and hope that works. Version 1.9.1 is live with those changes.

**Comment by lamka02sk** [comment]
No need to be sorry, the plugin is amazing, thank you!
Dark theme seems to be fixed now.
