### ISSUE TITLE
Info overlaid on image does not respect the borders of the screen

### ISSUE THREAD

**Issue by BiZkViT96** [jscher2000/View-Image-Info-Reborn-for-Firefox#5]
Thanks for the addon. As the title says, overlaid information stretches the window of the Firefox. It does not matter either the size of the image or the place from where the information window was called. And as you can see in the screenshots, the information window has an empty space on the right for no reason, and I have to scroll to the right to close the information popup. I tested without other add-ons, and the problem is present. I have a screen with a resolution of 1280x1024, and a Firefox 95 if it matters.

![2021-12-11 16_23_59-Window](https://user-images.githubusercontent.com/88586431/145671960-23249442-a214-47ab-a1ff-001bdabd86e3.png)
![2021-12-11 16_24_22-2761170157 jpg (Изображение JPEG, 1024 × 1024 пикселов) — Масштабированное (80%)](https://user-images.githubusercontent.com/88586431/145671961-f63e3613-0cc9-4d72-8e0f-f7a1f1c25c11.png)
![2021-12-11 16_24_30-f19f123cb9c599e3fef5741701ba6129 jpg (Изображение WEBP, 551 × 770 пикселов) — Mo](https://user-images.githubusercontent.com/88586431/145671965-ce652f40-6771-4599-b658-37f54fb8bfc9.png)

Links to images for convenience
https://kleo.ru/img/articles/tort-shokolad-kumkvat-iagody.jpg
https://i12.fotocdn.net/s121/49c94431d795ebd4/public_pin_l/2761170157.jpg
https://cdn4.imgbb.ru/community/182/1827985/201805/f19f123cb9c599e3fef5741701ba6129.jpg

**Comment by jscher2000** [comment]
Thank you for mentioning this. I overlooked this option when I fixed a different margin issue in May. I will correct it in the next update.

**Comment by jscher2000** [comment]
This should be fixed in today's updates.

**Comment by BiZkViT96** [comment]
Yes, its works! Thank you, for fast fix!
